### ISSUE TITLE
PGD based adversarial training issue? 

### ISSUE THREAD

**Issue by awaisrauf** [anonymous-sushi-armadillo/fast_is_better_than_free_imagenet#1]
In Alg1 of your [paper](https://openreview.net/attachment?id=BJx040EFvH&name=original_pdf), you described PGD Adversarial training but you only train your network with PGD attacked images. On the other hand, Madery et al. do it for both clean and adversarially attacks alternatively. Can you explain this, please? Thanks. 

**Reference of code** 
[Line115 for natural images](https://github.com/MadryLab/cifar10_challenge/blob/ecc870b3576beb010330324e690d2a6b48674fba/train.py#L115) 
[Line116 for adv images](https://github.com/MadryLab/cifar10_challenge/blob/ecc870b3576beb010330324e690d2a6b48674fba/train.py#L116)

**Comment by zjysteven** [comment]
Those two lines are just for recording purposes I think. The actual training step is at https://github.com/MadryLab/cifar10_challenge/blob/fdbb1a3d14aed7548ba67847fc27a7bc5da5e630/train.py#L137, where you can see that only adversarial images are used `sess.run(train_step, feed_dict=adv_dict)`.

**Comment by awaisrauf** [comment]
Got it. Thanks :)
